src/main/kotlin/io/github/v1servicenotification/domain/category/domain/NotificationCategory.kt, src/main/kotlin/io/github/v1servicenotification/global/entity/BaseUUIDEntity.kt
BaseUUIDEntity 조금 더 개선해봤습니다 :)
=> 🔀 :: (#6) BaseUUID Entity 만들기

src/main/kotlin/io/github/v1servicenotification/domain/category/presentation/dto/response/NotificationCategory.kt, src/main/kotlin/io/github/v1servicenotification/domain/category/service/QueryNotificationCategoryListService.kt, src/main/kotlin/io/github/v1servicenotification/global/entity/BaseUUIDEntity.kt
=> 🔀 :: (#23) 알림 카테고리 목록 Response id 추가

src/main/kotlin/io/github/v1servicenotification/domain/category/domain/repository/NotificationCategoryRepository.kt, src/main/kotlin/io/github/v1servicenotification/domain/category/presentation/CategoryController.kt, src/main/kotlin/io/github/v1servicenotification/domain/category/service/QueryActivatedCategory.kt
=> 🔀 :: (#21) 활성화된 알림 카테고리 목록

src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/NotificationSetting.kt, src/main/kotlin/io/github/v1servicenotification/domain/setting/facade/NotificationSettingFacade.kt, src/main/kotlin/io/github/v1servicenotification/domain/setting/service/ActivateNotificationCategoryService.kt, src/main/kotlin/io/github/v1servicenotification/domain/setting/service/DeActivateNotificationCategoryService.kt
코드가 너무 많이 겹치고, 중복되어서 따로 뺐습니다
close #27
=> 🔀 :: (#27) 알림 카테고리 비활성화 Api

build.gradle.kts, src/main/kotlin/io/github/v1servicenotification/global/config/FilterConfig.kt, src/main/kotlin/io/github/v1servicenotification/global/config/SecurityConfig.kt, src/main/kotlin/io/github/v1servicenotification/global/error/ErrorHandlingFilter.kt, src/main/kotlin/io/github/v1servicenotification/global/error/ErrorResponse.kt, src/main/kotlin/io/github/v1servicenotification/global/error/exception/ErrorCode.kt, src/main/kotlin/io/github/v1servicenotification/global/error/exception/NotificationException.kt
=> 🔀 :: (#29) Error Handling

src/main/kotlin/io/github/v1servicenotification/domain/category/exception/CategoryNotFoundException.kt, src/main/kotlin/io/github/v1servicenotification/domain/category/facade/CategoryFacade.kt, src/main/kotlin/io/github/v1servicenotification/domain/category/service/QueryActivatedCategory.kt, src/main/kotlin/io/github/v1servicenotification/domain/setting/facade/NotificationSettingFacade.kt, src/main/kotlin/io/github/v1servicenotification/global/error/exception/ErrorCode.kt, src/main/kotlin/io/github/v1servicenotification/global/error/exception/NotificationException.kt
=> 🔀 :: (#33) Category Not Found

src/main/kotlin/io/github/v1servicenotification/domain/setting/presentation/SettingController.kt
=> 🔀 :: (#35) 알림설정 Controller

src/main/kotlin/io/github/v1servicenotification/domain/detail/domain/NotificationDetail.kt, src/main/kotlin/io/github/v1servicenotification/domain/detail/domain/repository/NotificationDetailRepository.kt, src/main/kotlin/io/github/v1servicenotification/domain/detail/presentation/DetailController.kt, src/main/kotlin/io/github/v1servicenotification/domain/detail/presentation/dto/response/NotificationDetailListResponse.kt, src/main/kotlin/io/github/v1servicenotification/domain/detail/presentation/dto/response/NotificationDetailResponse.kt, src/main/kotlin/io/github/v1servicenotification/domain/detail/service/QueryNotificationDetailListService.kt
=> 🔀 :: (#37) 전송된 알림 목록 Api

.github/workflows/CI.yml
=> 🔀 :: (#28) CI 구축

build.gradle.kts, notification-domain/src/main/kotlin/io/github/v1servicenotification/category/Category.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/category/queryCategory/api/QueryActivatedCategory.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/category/queryCategory/api/QueryNotificationCategory.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/category/queryCategory/spi/CategoryRepositorySpi.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/Detail.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/queryDetail/spi/DetailRepositorySpi.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/setting/Setting.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/setting/activeSetting/spi/SettingRepositorySpi.kt, notification-infrastructure/build.gradle.kts, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/domain/CategoryEntity.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/domain/repository/NotificationCategoryRepository.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/facade/CategoryFacade.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/mapper/CategoryMapper.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/domain/DetailEntity.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/domain/repository/NotificationDetailRepository.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/mapper/DetailMapper.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/SettingEntity.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/SettingId.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/repository/NotificationSettingRepository.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/facade/NotificationSettingFacade.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/mapper/SettingMapper.kt
=> 🔀 :: (#46) Entity Mapper 만들기

.github/workflows/CI.yml
=> 🔀 :: (#50) Java version

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/DependencyVersions.kt, buildSrc/src/main/kotlin/PluginVersions.kt, notification-infrastructure/build.gradle.kts
=> 🔀 :: (#59) buildSrc 작성

notification-domain/src/main/kotlin/io/github/v1servicenotification/category/updateCategory/api/RemoveCategory.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/category/updateCategory/service/RemoveCategoryImpl.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/category/updateCategory/spi/UpdateCategoryRepositorySpi.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemoryCategoryRepository.kt, notification-domain/src/test/kotlin/io/github/v1servicenotification/category/CreateCategoryImplTest.kt, notification-domain/src/test/kotlin/io/github/v1servicenotification/category/RemoveCategoryImplTest.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/domain/repository/UpdateCategoryRepositoryImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/presentation/CategoryController.kt
=> 🔀 :: (#69) 알림 카테고리 제거

notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/mapper/DetailMapper.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/mapper/SettingMapper.kt
=> 🔀 :: (#72) Mapper UnMapped properties

notification-domain/src/main/kotlin/io/github/v1servicenotification/category/updateCategory/exception/CategoryNotFoundException.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/domain/repository/UpdateCategoryRepositoryImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/exception/CategoryNotFoundException.kt
=> 🔀 :: (#76) 자잘한 수정

buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/DependencyVersions.kt, notification-infrastructure/build.gradle.kts, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/global/fcm/FcmConfig.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/global/fcm/FcmService.kt
=> 🔀 :: (#42) Fcm 설정

notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/global/fcm/FcmService.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/global/fcm/dto/NotificationRequest.kt
실제 서비스에 사용될 spi는 추후에 추가하겠습니다.
close #79
=> 🔀 :: (#79) FCM message send 함수

notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/Detail.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/postDetail/api/PostGroupNotification.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/postDetail/service/PostGroupNotificationImpl.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/postDetail/spi/PostDetailFcmSpi.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/postDetail/spi/PostDetailRepositorySpi.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/postDetail/spi/PostDetailSettingRepositorySpi.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/queryDetail/service/QueryNotificationDetailImpl.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/queryDetail/spi/QueryDetailRepositorySpi.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemoryQueryDetailRepository.kt, notification-domain/src/test/kotlin/io/github/v1servicenotification/detail/QueryNotificationDetailImplTest.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/domain/repository/QueryDetailRepositoryImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/mapper/DetailMapper.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/repository/NotificationSettingRepository.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/repository/SettingRepositoryImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/global/fcm/FcmService.kt
User service에 userId를 통해서 Fcm token을 받아야합니다.
close #40
=> 🔀 :: (#40) 단체 알림 전송 Api

notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/postDetail/api/PostNotification.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/postDetail/service/PostNotificationImpl.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/postDetail/spi/PostDetailFcmSpi.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/postDetail/spi/PostDetailRepositorySpi.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/domain/repository/QueryDetailRepositoryImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/global/fcm/FcmService.kt
=> 🔀 :: (#41) 개별 알림 전송 Api

notification-domain/src/main/kotlin/io/github/v1servicenotification/error/ErrorCode.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/notification/exception/EmptyArgumentException.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/notification/presentation/QueueController.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/notification/presentation/dto/Group.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/notification/presentation/dto/Personal.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/repository/NotificationSettingRepository.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/repository/SettingRepositoryImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/global/config/CustomPayloadMethodArgumentResolver.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/global/config/SQSConfig.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/global/fcm/FcmConfig.kt, notification-infrastructure/src/main/resources/application.yml
=> 🔀 :: (#82) SQS Presenter

.github/workflows/prod-build.yaml, .github/workflows/stag-build.yaml
=> 🔀 :: (#92) workflow environment 추가

.github/workflows/prod-build.yaml, .github/workflows/stag-build.yaml, Dockerfile, notification-infrastructure/build.gradle.kts, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/global/fcm/FcmConfig.kt, notification-infrastructure/src/main/resources/application.yml
=> 🔀 :: (#94) FCM Config

notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/domain/CategoryEntity.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/domain/DetailEntity.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/SettingEntity.kt
=> 🔀 :: (#96) Boolean Type Entity

notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/domain/CategoryEntity.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/domain/DetailEntity.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/mapper/DetailMapper.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/mapper/DetailMapperImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/global/entity/BaseUUIDEntity.kt
=> 🔀 :: (#101) Detail Mapper 구현

notification-domain/src/main/kotlin/io/github/v1servicenotification/category/Category.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/category/updateCategory/service/CreateCategoryImpl.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/Detail.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/postDetail/service/PostGroupNotificationImpl.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/postDetail/service/PostNotificationImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/domain/DetailEntity.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/mapper/DetailMapperImpl.kt
=> 🔀 :: (#103) Null 처리

notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/Detail.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/queryDetail/spi/dto/DetailModel.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/presentation/dto/request/CreateCategoryRequest.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/domain/DetailEntity.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/domain/repository/vo/DetailVO.kt
=> 🔀 :: (#107) var private setter로 수정

notification-domain/src/main/kotlin/io/github/v1servicenotification/category/queryCategory/spi/QueryCategoryRepositorySpi.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/Detail.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/postDetail/service/PostGroupNotificationImpl.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/postDetail/service/PostNotificationImpl.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/postDetail/spi/PostDetailSettingRepositorySpi.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/postDetail/spi/PostDetailUserSpi.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemoryCategoryRepository.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemoryDetailRepository.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemorySettingRepository.kt, notification-domain/src/test/kotlin/io/github/v1servicenotification/detail/QueryNotificationDetailImplTest.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/domain/repository/CustomCategoryRepositoryImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/repository/CustomSettingRepositoryImpl.kt
=> 🔀 :: (#85) User Service Spi

notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemoryDetailRepository.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemoryFcm.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemorySettingRepository.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemoryUser.kt, notification-domain/src/test/kotlin/io/github/v1servicenotification/detail/CheckNotificationImplTest.kt, notification-domain/src/test/kotlin/io/github/v1servicenotification/detail/PostGroupNotificationImplTest.kt, notification-domain/src/test/kotlin/io/github/v1servicenotification/detail/PostNotificationImplTest.kt
=> 🔀 :: (#112) PostDetail Test

notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/domain/DetailEntity.kt
=> 🔀 :: (#116) Detail UserId Definition

.github/workflows/prod-build.yaml, .github/workflows/stag-build.yaml, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/global/error/ErrorHandlingFilter.kt
=> 🔀 :: (#119) github actions USER_URL 추가

.github/workflows/stag-build.yaml
=> 🔀 :: (#121) ECR migration

.github/workflows/prod-build.yaml, .github/workflows/stag-build.yaml
=> 🔀 :: (#123) Actions ECR 이전

notification-infrastructure/src/main/resources/application.yml
=> 🔀 :: (#125) Request Url Prefix

.github/CODEOWNERS
=> 🔀 :: (#129) CODEOWNERS 수정

notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/global/error/ErrorHandlingFilter.kt
=> 🔀 :: (#131) ErrorHandlingFilter NestedServletException Cause check

notification-domain/src/main/kotlin/io/github/v1servicenotification/category/queryCategory/api/QueryNotificationCategory.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/category/queryCategory/service/QueryNotificationCategoryImpl.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/category/queryCategory/spi/QueryCategoryRepositorySpi.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemoryCategoryRepository.kt, notification-domain/src/test/kotlin/io/github/v1servicenotification/category/CreateCategoryImplTest.kt, notification-domain/src/test/kotlin/io/github/v1servicenotification/category/QueryNotificationCategoryImplTest.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/domain/repository/CategoryRepository.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/domain/repository/CustomCategoryRepositoryImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/presentation/CategoryController.kt
https://mixolydian-hortensia-7d9.notion.site/2f9dc421687441608d487e26c5638d64
close #127
=> 🔀 :: (#127) 알림 카테고리 목록 Api 변경

notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/postDetail/service/PostGroupNotificationImpl.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/postDetail/spi/PostDetailSettingRepositorySpi.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/postDetail/spi/PostDetailUserSpi.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemorySettingRepository.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemoryUser.kt, notification-domain/src/test/kotlin/io/github/v1servicenotification/detail/PostGroupNotificationImplTest.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/domain/repository/CustomSettingRepositoryImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/user/domain/repository/CustomPostDetailUserImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/infrastructure/feign/client/UserClient.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/infrastructure/feign/client/dto/response/UserResponse.kt
코드만으로 이해가 어려울 수 있을 것같아서 주석 한 줄 남겨놨습니다.
close #133
=> 🔀 :: (#133) FCM 알림 발송 시 is_activated 체크 안함

notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/presentation/CategoryController.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/presentation/DetailController.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/presentation/SettingController.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/global/config/SecurityConfig.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/global/config/SwaggerConfig.kt, notification-infrastructure/src/main/resources/application.yml
=> 🔀 :: (#195) Swagger Operation, Tag 설정

notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/setting/presentation/SettingController.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/global/config/SwaggerConfig.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/global/util/CustomHttpStatus.kt
ApiResponses 어노테이션에 responseCode로 String type이 들어가야하는데, `An annotation argument must be a compile-time constant` 예외가 발생해서 커스텀 만들어서 작업진행함.
close #197
=> 🔀 :: (#197) Swagger Response Status 변경

notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/domain/repository/CustomDetailRepositoryImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/presentation/DetailController.kt
=> 🔀 :: (#204) 전송된 알림 목록 500 error

notification-domain/src/main/kotlin/io/github/v1servicenotification/category/Category.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/category/api/CategoryApi.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/category/api/response/CategoryElement.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/category/service/CategoryApiImpl.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/api/dto/response/DetailElement.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/service/DetailApiImpl.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/spi/dto/DetailModel.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/setting/service/SettingApiImpl.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemoryDetailRepository.kt, notification-domain/src/test/kotlin/io/github/v1servicenotification/category/CategoryImplTest.kt, notification-domain/src/test/kotlin/io/github/v1servicenotification/detail/DetailApiImplTest.kt, notification-domain/src/test/kotlin/io/github/v1servicenotification/setting/SettingApiImplTest.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/domain/CategoryEntity.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/presentation/CategoryController.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/presentation/dto/request/CreateCategoryRequest.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/domain/repository/CustomDetailRepositoryImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/domain/repository/vo/DetailVO.kt
=> 🔀 :: (#206) 카테고리 이미지 추가

notification-domain/src/main/kotlin/io/github/v1servicenotification/category/Category.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/category/Topic.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/category/api/CategoryApi.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/category/api/response/CategoryElement.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/category/service/CategoryApiImpl.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/api/dto/response/DetailElement.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/service/DetailApiImpl.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/spi/QueryDetailRepositorySpi.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/spi/dto/TopicDetailModel.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/setting/service/SettingApiImpl.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemoryDetailRepository.kt, notification-domain/src/test/kotlin/io/github/v1servicenotification/category/CategoryImplTest.kt, notification-domain/src/test/kotlin/io/github/v1servicenotification/detail/DetailApiImplTest.kt, notification-domain/src/test/kotlin/io/github/v1servicenotification/setting/SettingApiImplTest.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/domain/CategoryEntity.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/mapper/CategoryMapperImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/presentation/CategoryController.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/category/presentation/dto/request/CreateCategoryRequest.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/domain/repository/CustomDetailRepositoryImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/domain/repository/vo/DetailVO.kt
close #210
client 요청으로 topic을 enum 형태로 보내주면 좋겠다 해서 추가하였습니다
=> 🔀 :: (#210) 전송된 알림 목록 enum 추가

notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/service/DetailApiImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/presentation/DetailController.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/detail/presentation/dto/request/PostTestNotificationRequset.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/notification/presentation/QueueController.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/user/domain/repository/CustomPostDetailUserImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/infrastructure/feign/client/UserClient.kt
=> 🔀 :: (#212) 테스트 알림 발송 API

notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/spi/PostDetailUserSpi.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemoryUser.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/user/domain/repository/CustomPostDetailUserImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/infrastructure/feign/client/UserClient.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/infrastructure/feign/client/dto/request/ExcludeUserIdsRequest.kt
=> 🔀 :: (#80) 4096 Bytes Error 해결

notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/spi/PostDetailUserSpi.kt, notification-domain/src/main/kotlin/io/github/v1servicenotification/stubs/InMemoryUser.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/domain/user/domain/repository/CustomPostDetailUserImpl.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/infrastructure/feign/client/UserClient.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/infrastructure/feign/client/dto/request/ExcludeUserIdsRequest.kt, notification-infrastructure/src/main/kotlin/io/github/v1servicenotification/infrastructure/feign/client/dto/request/GetExcludeUserIdsRequest.kt
=> 🔀 :: (#82) 공지사항 알람 버그 해결

notification-domain/src/main/kotlin/io/github/v1servicenotification/detail/service/NotificationDetailApiImpl.kt
- 알림 detail db에 너무 많이 쌓여서 좋아요는 db 저장하지 않도록 수정하였습니다
=> 🔀 :: (#219) 좋아요 DB 저장 안하도록 수정
